# only certain consoles support all colors / mintty displays more colors
export COLOR_DEFAULT='\033[0m'
export COLOR_WHITE='\033[1;37m'
export COLOR_LIGHT_GREY='\033[0;37m'
export COLOR_MEDIUMGREY='\033[38;5;246m'
export COLOR_DARK_GREY='\033[1;30m'
export COLOR_BLACK='\033[0;30m'
export COLOR_PURPLE='\033[0;35m'
export COLOR_LIGHT_PURPLE='\033[1;35m'
export COLOR_LAVENDER='\033[38;5;183m'
export COLOR_BLUE='\033[0;34m'
export COLOR_LIGHT_BLUE='\033[1;34m'
export COLOR_SKYBLUE='\033[38;5;111m'
export COLOR_CYAN='\033[0;36m'
export COLOR_LIGHT_CYAN='\033[1;36m'
export COLOR_FOREST='\033[38;5;22m'
export COLOR_JADE='\033[38;5;35m'
export COLOR_GREEN='\033[0;32m'
export COLOR_LIGHT_GREEN='\033[1;32m'
export COLOR_MINTGREEN='\033[38;5;121m'
export COLOR_LIME='\033[38;5;154m'
export COLOR_YELLOW='\033[1;33m'
export COLOR_TAN='\033[38;5;179m'
export COLOR_LIGHTORANGE='\033[38;5;215m'
export COLOR_BROWN='\033[0;33m'
export COLOR_ORANGE='\033[38;5;203m'
export COLOR_LIGHTRED='\033[38;5;203m'
export COLOR_LIGHT_RED='\033[1;31m'
export COLOR_PINK='\033[38;5;211m'
export COLOR_HOTPINK='\033[38;5;198m'
export COLOR_RED='\033[0;31m'
export COLOR_MAROON='\033[38;5;52m'
# printf "${WHITE} COLOR DEFAULT\n"
export COLOR_PINK_BG='\033[48;5;211m'
export COLOR_ORANGE_BG='\033[48;5;203m'
export COLOR_SKYBLUE_BG='\033[48;5;111m';
export COLOR_MEDIUMGREY_BG='\033[48;5;246m'
export COLOR_LAVENDER_BG='\033[48;5;183m'
export COLOR_TAN_BG='\033[48;5;179m'
export COLOR_FOREST_BG='\033[48;5;22m'
export COLOR_MAROON_BG='\033[48;5;52m'
export COLOR_HOTPINK_BG='\033[48;5;198m'
export COLOR_MINTGREEN_BG='\033[48;5;121m'
export COLOR_LIGHTORANGE_BG='\033[48;5;215m'
export COLOR_LIGHTRED_BG='\033[48;5;203m'
export COLOR_JADE_BG='\033[48;5;35m'
export COLOR_LIME_BG='\033[48;5;154m'
export COLOR_UNDERLINE='\033[4m'
# export COLOR_COMBINED=$HOTPINK$MEDIUMGREY_BG$UNDERLINE

function echo_color {
    : output string line with color codes
    : usage color_echo string color_codes
    echo -e "$2${1}$COLOR_DEFAULT"
}

function color_list {
    : output list of defined color codes
    # only certain consoles support all colors / mintty displays more colors}$${COLOR_DEFAULT}"
    echo -e "${COLOR_DEFAULT}COLOR_DEFAULT${COLOR_DEFAULT}"
    echo -e "${COLOR_WHITE}COLOR_WHITE${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHT_GREY}COLOR_LIGHT_GREY${COLOR_DEFAULT}"
    echo -e "${COLOR_MEDIUMGREY}COLOR_MEDIUMGREY${COLOR_DEFAULT}"
    echo -e "${COLOR_DARK_GREY}COLOR_DARK_GREY${COLOR_DEFAULT}"
    echo -e "${COLOR_BLACK}COLOR_BLACK${COLOR_DEFAULT}"
    echo -e "${COLOR_PURPLE}COLOR_PURPLE${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHT_PURPLE}COLOR_LIGHT_PURPLE${COLOR_DEFAULT}"
    echo -e "${COLOR_LAVENDER}COLOR_LAVENDER${COLOR_DEFAULT}"
    echo -e "${COLOR_BLUE}COLOR_BLUE${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHT_BLUE}COLOR_LIGHT_BLUE${COLOR_DEFAULT}"
    echo -e "${COLOR_SKYBLUE}COLOR_SKYBLUE${COLOR_DEFAULT}"
    echo -e "${COLOR_CYAN}COLOR_CYAN${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHT_CYAN}COLOR_LIGHT_CYAN${COLOR_DEFAULT}"
    echo -e "${COLOR_FOREST}COLOR_FOREST${COLOR_DEFAULT}"
    echo -e "${COLOR_JADE}COLOR_JADE${COLOR_DEFAULT}"
    echo -e "${COLOR_GREEN}COLOR_GREEN${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHT_GREEN}COLOR_LIGHT_GREEN${COLOR_DEFAULT}"
    echo -e "${COLOR_MINTGREEN}COLOR_MINTGREEN${COLOR_DEFAULT}"
    echo -e "${COLOR_LIME}COLOR_LIME${COLOR_DEFAULT}"
    echo -e "${COLOR_YELLOW}COLOR_YELLOW${COLOR_DEFAULT}"
    echo -e "${COLOR_TAN}COLOR_TAN${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHTORANGE}COLOR_LIGHTORANGE${COLOR_DEFAULT}"
    echo -e "${COLOR_BROWN}COLOR_BROWN${COLOR_DEFAULT}"
    echo -e "${COLOR_ORANGE}COLOR_ORANGE${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHTRED}COLOR_LIGHTRED${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHT_RED}COLOR_LIGHT_RED${COLOR_DEFAULT}"
    echo -e "${COLOR_PINK}COLOR_PINK${COLOR_DEFAULT}"
    echo -e "${COLOR_HOTPINK}COLOR_HOTPINK${COLOR_DEFAULT}"
    echo -e "${COLOR_RED}COLOR_RED${COLOR_DEFAULT}"
    echo -e "${COLOR_MAROON}COLOR_MAROON${COLOR_DEFAULT}"
    echo -e "${COLOR_PINK_BG}COLOR_PINK_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_ORANGE_BG}COLOR_ORANGE_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_SKYBLUE_BG}COLOR_SKYBLUE_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_MEDIUMGREY_BG}COLOR_MEDIUMGREY_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_LAVENDER_BG}COLOR_LAVENDER_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_TAN_BG}COLOR_TAN_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_FOREST_BG}COLOR_FOREST_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_MAROON_BG}COLOR_MAROON_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_HOTPINK_BG}COLOR_HOTPINK_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_MINTGREEN_BG}COLOR_MINTGREEN_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHTORANGE_BG}COLOR_LIGHTORANGE_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_LIGHTRED_BG}COLOR_LIGHTRED_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_JADE_BG}COLOR_JADE_BG${COLOR_DEFAULT}"
    echo -e "${COLOR_LIME_BG}COLOR_LIME_BG${COLOR_DEFAULT}"
}